var examples =
[
    [ "CreateBuffer.cs", "_create_buffer_8cs-example.html", null ],
    [ "SelectBox.cs", "_select_box_8cs-example.html", null ],
    [ "EditAttributes.cs", "_edit_attributes_8cs-example.html", null ],
    [ "IntersectionLength.cs", "_intersection_length_8cs-example.html", null ],
    [ "MarkPoints.cs", "_mark_points_8cs-example.html", null ],
    [ "Tracking.cs", "_tracking_8cs-example.html", null ],
    [ "ZoomToValues.cs", "_zoom_to_values_8cs-example.html", null ],
    [ "MinimalDistance.cs", "_minimal_distance_8cs-example.html", null ],
    [ "ToolTip.cs", "_tool_tip_8cs-example.html", null ],
    [ "SplitByAttribute.cs", "_split_by_attribute_8cs-example.html", null ],
    [ "Segmentation.cs", "_segmentation_8cs-example.html", null ],
    [ "RemoveShape.cs", "_remove_shape_8cs-example.html", null ],
    [ "LabelSelection.cs", "_label_selection_8cs-example.html", null ],
    [ "PointIcons.cs", "_point_icons_8cs-example.html", null ],
    [ "LinePattern.cs", "_line_pattern_8cs-example.html", null ],
    [ "ImageLabels.cs", "_image_labels_8cs-example.html", null ],
    [ "GeoProjection.cs", "_geo_projection_8cs-example.html", null ],
    [ "CalculateArea.cs", "_calculate_area_8cs-example.html", null ],
    [ "CreatePointShapefile.cs", "_create_point_shapefile_8cs-example.html", null ],
    [ "CreatePolygonShapefile.cs", "_create_polygon_shapefile_8cs-example.html", null ],
    [ "AddLayers.cs", "_add_layers_8cs-example.html", null ],
    [ "ShapefileToDrawingLayer.cs", "_shapefile_to_drawing_layer_8cs-example.html", null ],
    [ "SelectByQuery.cs", "_select_by_query_8cs-example.html", null ],
    [ "PolygonsWithHoles.cs", "_polygons_with_holes_8cs-example.html", null ],
    [ "SelectByDistance.cs", "_select_by_distance_8cs-example.html", null ],
    [ "SortLayers.cs", "_sort_layers_8cs-example.html", null ],
    [ "ShowAttributes.cs", "_show_attributes_8cs-example.html", null ],
    [ "AddCategoryRange.cs", "_add_category_range_8cs-example.html", null ],
    [ "GenerateLabelsManually.cs", "_generate_labels_manually_8cs-example.html", null ],
    [ "TrackCars.cs", "_track_cars_8cs-example.html", null ]
];